/*
 * Regenerate the vendored Noto subsets (run on demand: `bun run fonts:update`).
 *
 * Noto changes very rarely, so the .woff2 files are committed and the normal
 * build stays hermetic (offline/CI-safe, deterministic). Run this ONLY when the
 * text in src/translations.ts gains new characters — especially Chinese ones —
 * so the subset covers them. It re-extracts the exact glyph set, fetches the
 * matching Noto Sans / Noto Sans SC / Noto Sans TC subsets, and rewrites
 * src/fonts/*.woff2 and src/fonts.ts (with fresh unicode-range values).
 *
 * The two Chinese glyph sets are extracted per language (from the imported
 * translation objects, not the raw file): Simplified and Traditional pages each
 * ship only their own script, and shared codepoints get the right regional
 * glyph variant from their respective family (SC = PRC forms, TC = Taiwan MOE).
 */

import { translations } from '../src/translations.ts';

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const source = await Bun.file('src/translations.ts').text();

function unique(text: string, pred: (cp: number, ch: string) => boolean): string {
  const set = new Set<string>();
  for (const ch of text) if (pred(ch.codePointAt(0)!, ch)) set.add(ch);
  return [...set].sort().join('');
}

const isLatin = (cp: number): boolean =>
  (cp >= 0x20 && cp <= 0x7e) ||
  (cp >= 0xa0 && cp <= 0x24f) ||
  (cp >= 0x2010 && cp <= 0x203a) ||
  cp === 0x20ac ||
  cp === 0xb0;
const isCjk = (cp: number, ch: string): boolean =>
  (cp >= 0x4e00 && cp <= 0x9fff) || '（）：，。—·、'.includes(ch);

const latin = unique(source, (cp) => isLatin(cp));
const sc = unique(JSON.stringify(translations.zh), isCjk);
const tc = unique(JSON.stringify(translations['zh-hant']), isCjk);

console.log(`Glyphs — Latin: ${latin.length}, SC: ${sc.length}, TC: ${tc.length}`);

async function subset(family: string, text: string): Promise<{ url: string; range: string }> {
  const cssUrl =
    `https://fonts.googleapis.com/css2?family=${family}:wght@400..800` +
    `&text=${encodeURIComponent(text)}&display=swap`;
  const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text();
  const url = css.match(/url\((https:\/\/[^)]+)\)/)?.[1];
  const range = css.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
  if (!url || !range) throw new Error(`Could not parse @font-face for ${family}`);
  return { url, range };
}

const [latinFont, scFont, tcFont] = await Promise.all([
  subset('Noto+Sans', latin),
  subset('Noto+Sans+SC', sc),
  subset('Noto+Sans+TC', tc),
]);

async function download(url: string, path: string): Promise<void> {
  const bytes = await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer();
  await Bun.write(path, bytes);
  console.log(`  wrote ${path} (${Math.round(bytes.byteLength / 1024)} KB)`);
}

await download(latinFont.url, 'src/fonts/noto-sans-latin.woff2');
await download(scFont.url, 'src/fonts/noto-sans-sc.woff2');
await download(tcFont.url, 'src/fonts/noto-sans-tc.woff2');

const fontsTs = `/*
 * Self-hosted Noto Sans (Latin) + Noto Sans SC/TC (subset to the glyphs used).
 * Generated by scripts/update-fonts.ts — run \`bun run fonts:update\` to refresh.
 *
 * The woff2 files are imported (not referenced via CSS \`url()\`): Bun inlines
 * CSS-referenced fonts as base64, but a JS import goes through the \`file\` loader
 * and is emitted as a separate hashed asset. We then inject the @font-face rules
 * at runtime with those build-time URLs. \`unicode-range\` keeps the CJK files lazy,
 * and each page's \`--font\` stack names only its own CJK family (SC or TC), so a
 * visitor never downloads a Chinese subset they don't read.
 *
 * A named font (not \`system-ui\`) is required for accurate pretext measurement.
 */

import latinUrl from './fonts/noto-sans-latin.woff2';
import scUrl from './fonts/noto-sans-sc.woff2';
import tcUrl from './fonts/noto-sans-tc.woff2';

const LATIN_RANGE = '${latinFont.range}';
const SC_RANGE = '${scFont.range}';
const TC_RANGE = '${tcFont.range}';

const css = [
  \`@font-face{font-family:'Noto Sans';font-style:normal;font-weight:400 800;font-display:swap;src:url(\${latinUrl}) format('woff2');unicode-range:\${LATIN_RANGE};}\`,
  \`@font-face{font-family:'Noto Sans SC';font-style:normal;font-weight:400 800;font-display:swap;src:url(\${scUrl}) format('woff2');unicode-range:\${SC_RANGE};}\`,
  \`@font-face{font-family:'Noto Sans TC';font-style:normal;font-weight:400 800;font-display:swap;src:url(\${tcUrl}) format('woff2');unicode-range:\${TC_RANGE};}\`,
].join('');

const style = document.createElement('style');
style.textContent = css;
document.head.appendChild(style);
`;

await Bun.write('src/fonts.ts', fontsTs);
console.log('  wrote src/fonts.ts');
console.log('\n✓ Fonts regenerated. Rebuild with `bun run build`.');
