/*
 * Regenerate the vendored Noto subsets (run on demand: `bun run fonts:update`).
 *
 * Noto changes very rarely, so the .woff2 files are committed and the normal
 * build stays hermetic (offline/CI-safe, deterministic). Run this ONLY when the
 * user-visible text gains new characters — especially Chinese ones — so the
 * subset covers them. It re-extracts the exact glyph set, fetches the matching
 * Noto Sans / Noto Sans SC / Noto Sans TC subsets, and rewrites
 * src/fonts/*.woff2 and src/fonts.ts (with fresh unicode-range values).
 *
 * The glyph sets come from [scripts/glyphs.ts](scripts/glyphs.ts), shared with
 * the coverage guard (scripts/fonts-coverage.test.ts) that fails whenever the
 * text drifts ahead of the committed subsets. Shared CJK codepoints get the
 * right regional glyph variant from their respective family (SC = PRC forms,
 * TC = Taiwan MOE).
 */

import { glyphSets } from "./glyphs.ts";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const { latin, sc, tc } = await glyphSets();

console.log(
  `Glyphs — Latin: ${latin.length}, SC: ${sc.length}, TC: ${tc.length}`,
);

async function subset(
  family: string,
  text: string,
): Promise<{ url: string; range: string }> {
  const cssUrl =
    `https://fonts.googleapis.com/css2?family=${family}:wght@400..800` +
    `&text=${encodeURIComponent(text)}&display=swap`;
  const response = await fetch(cssUrl, { headers: { "User-Agent": UA } });
  if (!response.ok) {
    throw new Error(
      `Fetching CSS for ${family} failed: HTTP ${response.status}`,
    );
  }
  const css = await response.text();
  const url = css.match(/url\((https:\/\/[^)]+)\)/)?.[1];
  const range = css.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
  if (!url || !range) {
    throw new Error(`Could not parse @font-face for ${family}`);
  }
  return { url, range };
}

const [latinFont, scFont, tcFont] = await Promise.all([
  subset("Noto+Sans", latin),
  subset("Noto+Sans+SC", sc),
  subset("Noto+Sans+TC", tc),
]);

async function download(url: string, path: string): Promise<void> {
  const response = await fetch(url, { headers: { "User-Agent": UA } });
  if (!response.ok) {
    throw new Error(`Downloading ${url} failed: HTTP ${response.status}`);
  }
  const bytes = await response.arrayBuffer();
  await Bun.write(path, bytes);
  console.log(`  wrote ${path} (${Math.round(bytes.byteLength / 1024)} KB)`);
}

await download(latinFont.url, "src/fonts/noto-sans-latin.woff2");
await download(scFont.url, "src/fonts/noto-sans-sc.woff2");
await download(tcFont.url, "src/fonts/noto-sans-tc.woff2");

const fontsTs = `/*
 * Self-hosted Noto Sans (Latin) + Noto Sans SC/TC (subset to the glyphs used).
 * Generated by scripts/update-fonts.ts — run \`bun run fonts:update\` to refresh.
 *
 * The woff2 files are imported (not referenced via CSS \`url()\`): Bun inlines
 * CSS-referenced fonts as base64, but a JS import goes through the \`file\` loader
 * and is emitted as a separate hashed asset. \`unicode-range\` keeps the CJK files
 * lazy, and each page's \`--font\` stack names only its own CJK family (SC or TC),
 * so a visitor never downloads a Chinese subset they don't read.
 *
 * The @font-face rules exist in two places, on purpose:
 *   - the SSG build ([scripts/build.ts](scripts/build.ts)) inlines them into each
 *     pre-rendered <head> (fonts load before JS, and no-JS visitors get them too);
 *   - this module injects them at runtime as a fallback for the dev shell, and
 *     skips itself when the build-injected <style data-fonts> is already present.
 *
 * A named font (not \`system-ui\`) is required for accurate pretext measurement.
 */

import latinUrl from "./fonts/noto-sans-latin.woff2";
import scUrl from "./fonts/noto-sans-sc.woff2";
import tcUrl from "./fonts/noto-sans-tc.woff2";

const LATIN_RANGE =
  "${latinFont.range}";
const SC_RANGE =
  "${scFont.range}";
const TC_RANGE =
  "${tcFont.range}";

/** The three subsets with their build-emitted URLs and unicode ranges. */
export const FONT_FACES = [
  { family: "Noto Sans", url: latinUrl, range: LATIN_RANGE },
  { family: "Noto Sans SC", url: scUrl, range: SC_RANGE },
  { family: "Noto Sans TC", url: tcUrl, range: TC_RANGE },
] as const;

/** @font-face rules for the given subset URLs (SSG passes its own hashed paths). */
export function fontFaceCss(
  faces: readonly { family: string; url: string; range: string }[],
): string {
  return faces
    .map(
      (f) =>
        \`@font-face{font-family:'\${f.family}';font-style:normal;font-weight:400 800;font-display:swap;src:url(\${f.url}) format('woff2');unicode-range:\${f.range};}\`,
    )
    .join("");
}

// Runtime fallback for the dev shell; pre-rendered pages already carry the rules.
if (
  typeof document !== "undefined" &&
  !document.querySelector("style[data-fonts]")
) {
  const style = document.createElement("style");
  style.dataset.fonts = "runtime";
  style.textContent = fontFaceCss(FONT_FACES);
  document.head.appendChild(style);
}
`;

await Bun.write("src/fonts.ts", fontsTs);
// The template above is written pre-formatted, but the ranges vary in length
// from run to run — let the project's formatter have the last word so a
// regeneration never shows up as style churn in the diff.
await Bun.$`deno fmt --quiet src/fonts.ts`.nothrow();
console.log("  wrote src/fonts.ts");
console.log("\n✓ Fonts regenerated. Rebuild with `bun run build`.");
